#############################################################################
# Makefile for building: duckracer2
# Generated by qmake (2.01a) (Qt 4.8.2) on: So. Jun 24 17:44:53 2012
# Project:  duckracer2.pro
# Template: app
# Command: /usr/bin/qmake -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile duckracer2.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/QtCore -I/usr/include/QtGui -I/usr/include -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib64 -lQtGui -L/usr/lib64 -L/usr/X11R6/lib64 -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = main.cpp \
		duckracer.cpp \
		dlgconfigure.cpp \
		wdgscan.cpp \
		wdgprizes.cpp \
		wdgprintlists.cpp \
		wdgprintlabels.cpp \
		prizelistmodel.cpp \
		scanner.cpp \
		duckplacemodel.cpp moc_duckracer.cpp \
		moc_dlgconfigure.cpp \
		moc_wdgscan.cpp \
		moc_wdgprizes.cpp \
		moc_wdgprintlists.cpp \
		moc_wdgprintlabels.cpp \
		moc_prizelistmodel.cpp \
		moc_scanner.cpp \
		moc_duckplacemodel.cpp
OBJECTS       = main.o \
		duckracer.o \
		dlgconfigure.o \
		wdgscan.o \
		wdgprizes.o \
		wdgprintlists.o \
		wdgprintlabels.o \
		prizelistmodel.o \
		scanner.o \
		duckplacemodel.o \
		moc_duckracer.o \
		moc_dlgconfigure.o \
		moc_wdgscan.o \
		moc_wdgprizes.o \
		moc_wdgprintlists.o \
		moc_wdgprintlabels.o \
		moc_prizelistmodel.o \
		moc_scanner.o \
		moc_duckplacemodel.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		duckracer2.pro
QMAKE_TARGET  = duckracer2
DESTDIR       = 
TARGET        = duckracer2

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: duckracer2.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib64/libQtGui.prl \
		/usr/lib64/libQtCore.prl
	$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile duckracer2.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib64/libQtGui.prl:
/usr/lib64/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -spec /usr/share/qt4/mkspecs/linux-g++ -o Makefile duckracer2.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/duckracer21.0.0 || $(MKDIR) .tmp/duckracer21.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/duckracer21.0.0/ && $(COPY_FILE) --parents duckracer.h dlgconfigure.h wdgscan.h wdgprizes.h wdgprintlists.h wdgprintlabels.h prizelistmodel.h scanner.h duckplacemodel.h .tmp/duckracer21.0.0/ && $(COPY_FILE) --parents main.cpp duckracer.cpp dlgconfigure.cpp wdgscan.cpp wdgprizes.cpp wdgprintlists.cpp wdgprintlabels.cpp prizelistmodel.cpp scanner.cpp duckplacemodel.cpp .tmp/duckracer21.0.0/ && (cd `dirname .tmp/duckracer21.0.0` && $(TAR) duckracer21.0.0.tar duckracer21.0.0 && $(COMPRESS) duckracer21.0.0.tar) && $(MOVE) `dirname .tmp/duckracer21.0.0`/duckracer21.0.0.tar.gz . && $(DEL_FILE) -r .tmp/duckracer21.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_duckracer.cpp moc_dlgconfigure.cpp moc_wdgscan.cpp moc_wdgprizes.cpp moc_wdgprintlists.cpp moc_wdgprintlabels.cpp moc_prizelistmodel.cpp moc_scanner.cpp moc_duckplacemodel.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_duckracer.cpp moc_dlgconfigure.cpp moc_wdgscan.cpp moc_wdgprizes.cpp moc_wdgprintlists.cpp moc_wdgprintlabels.cpp moc_prizelistmodel.cpp moc_scanner.cpp moc_duckplacemodel.cpp
moc_duckracer.cpp: duckracer.h
	/usr/bin/moc $(DEFINES) $(INCPATH) duckracer.h -o moc_duckracer.cpp

moc_dlgconfigure.cpp: dlgconfigure.h
	/usr/bin/moc $(DEFINES) $(INCPATH) dlgconfigure.h -o moc_dlgconfigure.cpp

moc_wdgscan.cpp: wdgscan.h
	/usr/bin/moc $(DEFINES) $(INCPATH) wdgscan.h -o moc_wdgscan.cpp

moc_wdgprizes.cpp: wdgprizes.h
	/usr/bin/moc $(DEFINES) $(INCPATH) wdgprizes.h -o moc_wdgprizes.cpp

moc_wdgprintlists.cpp: wdgprintlists.h
	/usr/bin/moc $(DEFINES) $(INCPATH) wdgprintlists.h -o moc_wdgprintlists.cpp

moc_wdgprintlabels.cpp: wdgprintlabels.h
	/usr/bin/moc $(DEFINES) $(INCPATH) wdgprintlabels.h -o moc_wdgprintlabels.cpp

moc_prizelistmodel.cpp: prizelistmodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) prizelistmodel.h -o moc_prizelistmodel.cpp

moc_scanner.cpp: scanner.h
	/usr/bin/moc $(DEFINES) $(INCPATH) scanner.h -o moc_scanner.cpp

moc_duckplacemodel.cpp: duckplacemodel.h
	/usr/bin/moc $(DEFINES) $(INCPATH) duckplacemodel.h -o moc_duckplacemodel.cpp

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean 

####### Compile

main.o: main.cpp duckracer.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

duckracer.o: duckracer.cpp duckracer.h \
		dlgconfigure.h \
		wdgprizes.h \
		wdgscan.h \
		wdgprintlabels.h \
		wdgprintlists.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o duckracer.o duckracer.cpp

dlgconfigure.o: dlgconfigure.cpp dlgconfigure.h \
		scanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o dlgconfigure.o dlgconfigure.cpp

wdgscan.o: wdgscan.cpp wdgscan.h \
		duckplacemodel.h \
		scanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wdgscan.o wdgscan.cpp

wdgprizes.o: wdgprizes.cpp wdgprizes.h \
		prizelistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wdgprizes.o wdgprizes.cpp

wdgprintlists.o: wdgprintlists.cpp wdgprintlists.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wdgprintlists.o wdgprintlists.cpp

wdgprintlabels.o: wdgprintlabels.cpp wdgprintlabels.h \
		scanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o wdgprintlabels.o wdgprintlabels.cpp

prizelistmodel.o: prizelistmodel.cpp prizelistmodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o prizelistmodel.o prizelistmodel.cpp

scanner.o: scanner.cpp scanner.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o scanner.o scanner.cpp

duckplacemodel.o: duckplacemodel.cpp duckplacemodel.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o duckplacemodel.o duckplacemodel.cpp

moc_duckracer.o: moc_duckracer.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_duckracer.o moc_duckracer.cpp

moc_dlgconfigure.o: moc_dlgconfigure.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_dlgconfigure.o moc_dlgconfigure.cpp

moc_wdgscan.o: moc_wdgscan.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wdgscan.o moc_wdgscan.cpp

moc_wdgprizes.o: moc_wdgprizes.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wdgprizes.o moc_wdgprizes.cpp

moc_wdgprintlists.o: moc_wdgprintlists.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wdgprintlists.o moc_wdgprintlists.cpp

moc_wdgprintlabels.o: moc_wdgprintlabels.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_wdgprintlabels.o moc_wdgprintlabels.cpp

moc_prizelistmodel.o: moc_prizelistmodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_prizelistmodel.o moc_prizelistmodel.cpp

moc_scanner.o: moc_scanner.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_scanner.o moc_scanner.cpp

moc_duckplacemodel.o: moc_duckplacemodel.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_duckplacemodel.o moc_duckplacemodel.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

